import type { TemplateRecord } from "./template-records";

export const templateRecordsSeedVersion = "2026-06-01-template-records-v1";

export const templateRecordsSeed: TemplateRecord[] = [
  {
    id: "REC-1001",
    project: "Claims intake redesign",
    owner: "Maya Chen",
    status: "In Progress",
    priority: "High",
    category: "Operations",
    impactScore: 91,
    updatedAt: "2026-05-28",
    summary:
      "Reduce duplicate claim entry by grouping source documents and extracted facts.",
  },
  {
    id: "REC-1002",
    project: "Vendor risk register",
    owner: "Jon Bell",
    status: "Review",
    priority: "Medium",
    category: "Compliance",
    impactScore: 72,
    updatedAt: "2026-05-24",
    summary:
      "Track vendor controls, residual risk, evidence links, and review cadence.",
  },
  {
    id: "REC-1003",
    project: "Portfolio signal monitor",
    owner: "Amara Singh",
    status: "Backlog",
    priority: "Medium",
    category: "Research",
    impactScore: 64,
    updatedAt: "2026-05-20",
    summary:
      "Surface notable movement from filings, analyst notes, and internal tags.",
  },
  {
    id: "REC-1004",
    project: "Incident command center",
    owner: "Elias Park",
    status: "Blocked",
    priority: "High",
    category: "Security",
    impactScore: 88,
    updatedAt: "2026-05-18",
    summary:
      "Waiting on identity provider scopes before closing escalation workflows.",
  },
  {
    id: "REC-1005",
    project: "Clinical trial tracker",
    owner: "Nora Patel",
    status: "Done",
    priority: "High",
    category: "Healthcare",
    impactScore: 95,
    updatedAt: "2026-05-30",
    summary:
      "Summarize recruitment status, site readiness, and protocol deviation counts.",
  },
  {
    id: "REC-1006",
    project: "Grant opportunity board",
    owner: "Luca Moreno",
    status: "In Progress",
    priority: "Low",
    category: "Nonprofit",
    impactScore: 58,
    updatedAt: "2026-05-14",
    summary:
      "Prioritize grants by eligibility fit, award size, deadlines, and program area.",
  },
  {
    id: "REC-1007",
    project: "Factory downtime map",
    owner: "Iris Kim",
    status: "Review",
    priority: "High",
    category: "Manufacturing",
    impactScore: 83,
    updatedAt: "2026-05-26",
    summary:
      "Compare downtime events by line, root cause, shift, and maintenance action.",
  },
  {
    id: "REC-1008",
    project: "Policy exception queue",
    owner: "Theo Wright",
    status: "Backlog",
    priority: "Medium",
    category: "Compliance",
    impactScore: 69,
    updatedAt: "2026-05-12",
    summary:
      "Route exceptions by severity, approver, expiration date, and mitigation plan.",
  },
  {
    id: "REC-1009",
    project: "Revenue leakage audit",
    owner: "Priya Shah",
    status: "In Progress",
    priority: "High",
    category: "Finance",
    impactScore: 89,
    updatedAt: "2026-05-22",
    summary:
      "Find billing mismatches across contracts, usage records, and invoice lines.",
  },
  {
    id: "REC-1010",
    project: "Customer health workspace",
    owner: "Sam Rivera",
    status: "Done",
    priority: "Medium",
    category: "Customer Success",
    impactScore: 77,
    updatedAt: "2026-05-16",
    summary:
      "Blend support history, product activity, renewal dates, and sentiment notes.",
  },
  {
    id: "REC-1011",
    project: "Permit review dashboard",
    owner: "Hannah Lee",
    status: "Review",
    priority: "Medium",
    category: "Public Sector",
    impactScore: 71,
    updatedAt: "2026-05-10",
    summary:
      "Measure queue age, document completeness, reviewer load, and public comments.",
  },
  {
    id: "REC-1012",
    project: "Energy usage explorer",
    owner: "Mateo Cruz",
    status: "In Progress",
    priority: "Low",
    category: "Facilities",
    impactScore: 61,
    updatedAt: "2026-05-08",
    summary:
      "Correlate energy spikes with weather, occupancy, equipment, and schedules.",
  },
  {
    id: "REC-1013",
    project: "Source quality review",
    owner: "Avery Brooks",
    status: "Done",
    priority: "Medium",
    category: "Research",
    impactScore: 74,
    updatedAt: "2026-05-06",
    summary:
      "Grade sources by freshness, authoritativeness, bias signals, and citation depth.",
  },
  {
    id: "REC-1014",
    project: "Claims fraud triage",
    owner: "Maya Chen",
    status: "Backlog",
    priority: "High",
    category: "Operations",
    impactScore: 86,
    updatedAt: "2026-05-02",
    summary:
      "Flag suspicious patterns with claim history, provider data, and external signals.",
  },
  {
    id: "REC-1015",
    project: "Legal matter timeline",
    owner: "Noah Grant",
    status: "Blocked",
    priority: "Medium",
    category: "Legal",
    impactScore: 67,
    updatedAt: "2026-04-30",
    summary:
      "Blocked until privileged document handling is finalized with counsel.",
  },
  {
    id: "REC-1016",
    project: "Procurement savings finder",
    owner: "Iris Kim",
    status: "In Progress",
    priority: "High",
    category: "Finance",
    impactScore: 84,
    updatedAt: "2026-04-27",
    summary:
      "Compare spend, supplier overlap, contract terms, and renewal windows.",
  },
  {
    id: "REC-1017",
    project: "Dataset lineage browser",
    owner: "Elias Park",
    status: "Review",
    priority: "High",
    category: "Data Platform",
    impactScore: 90,
    updatedAt: "2026-04-25",
    summary:
      "Show upstream sources, transformations, freshness, owners, and consuming apps.",
  },
  {
    id: "REC-1018",
    project: "Training cohort planner",
    owner: "Luca Moreno",
    status: "Done",
    priority: "Low",
    category: "People",
    impactScore: 55,
    updatedAt: "2026-04-22",
    summary:
      "Group employees by role, skill gaps, manager input, and preferred schedule.",
  },
  {
    id: "REC-1019",
    project: "Competitor pricing watch",
    owner: "Amara Singh",
    status: "In Progress",
    priority: "Medium",
    category: "Market Intel",
    impactScore: 73,
    updatedAt: "2026-04-19",
    summary:
      "Track pricing page changes, packaging shifts, promotions, and quote notes.",
  },
  {
    id: "REC-1020",
    project: "Support backlog sweeper",
    owner: "Sam Rivera",
    status: "Backlog",
    priority: "Medium",
    category: "Customer Success",
    impactScore: 66,
    updatedAt: "2026-04-15",
    summary:
      "Cluster aging support tickets by account, theme, sentiment, and ownership.",
  },
  {
    id: "REC-1021",
    project: "Data retention matrix",
    owner: "Jon Bell",
    status: "Review",
    priority: "High",
    category: "Compliance",
    impactScore: 82,
    updatedAt: "2026-04-12",
    summary:
      "Map datasets to retention policy, legal hold status, owner, and delete path.",
  },
  {
    id: "REC-1022",
    project: "Route capacity model",
    owner: "Theo Wright",
    status: "In Progress",
    priority: "Medium",
    category: "Logistics",
    impactScore: 76,
    updatedAt: "2026-04-09",
    summary:
      "Balance route demand, driver hours, constraints, and service-level targets.",
  },
  {
    id: "REC-1023",
    project: "Content freshness audit",
    owner: "Hannah Lee",
    status: "Done",
    priority: "Low",
    category: "Marketing",
    impactScore: 57,
    updatedAt: "2026-04-06",
    summary:
      "Rank help docs and landing pages by traffic, age, conversions, and owner.",
  },
  {
    id: "REC-1024",
    project: "Lab inventory ledger",
    owner: "Nora Patel",
    status: "Blocked",
    priority: "High",
    category: "Healthcare",
    impactScore: 80,
    updatedAt: "2026-04-03",
    summary: "Blocked while barcode scanner export format is being normalized.",
  },
  {
    id: "REC-1025",
    project: "Renewal risk brief",
    owner: "Priya Shah",
    status: "In Progress",
    priority: "High",
    category: "Customer Success",
    impactScore: 87,
    updatedAt: "2026-03-30",
    summary:
      "Create concise renewal briefs from usage, outcomes, tickets, and stakeholders.",
  },
  {
    id: "REC-1026",
    project: "Asset depreciation view",
    owner: "Mateo Cruz",
    status: "Review",
    priority: "Medium",
    category: "Finance",
    impactScore: 70,
    updatedAt: "2026-03-26",
    summary:
      "Compare asset book value, age, replacement timing, and maintenance history.",
  },
  {
    id: "REC-1027",
    project: "Executive research digest",
    owner: "Avery Brooks",
    status: "Done",
    priority: "Medium",
    category: "Research",
    impactScore: 78,
    updatedAt: "2026-03-23",
    summary:
      "Compress weekly findings into themes, sources, confidence, and next actions.",
  },
  {
    id: "REC-1028",
    project: "Change approval queue",
    owner: "Noah Grant",
    status: "Backlog",
    priority: "Medium",
    category: "Operations",
    impactScore: 63,
    updatedAt: "2026-03-20",
    summary:
      "Prioritize change requests by business risk, readiness, blast radius, and date.",
  },
  {
    id: "REC-1029",
    project: "Fundraising pipeline map",
    owner: "Luca Moreno",
    status: "In Progress",
    priority: "Medium",
    category: "Nonprofit",
    impactScore: 68,
    updatedAt: "2026-03-17",
    summary:
      "Track prospects, touchpoints, giving history, program match, and next step.",
  },
  {
    id: "REC-1030",
    project: "Audit evidence binder",
    owner: "Jon Bell",
    status: "Review",
    priority: "High",
    category: "Compliance",
    impactScore: 85,
    updatedAt: "2026-03-14",
    summary:
      "Collect control evidence with owner attestations, timestamps, and gaps.",
  },
  {
    id: "REC-1031",
    project: "Patient outreach list",
    owner: "Nora Patel",
    status: "Backlog",
    priority: "High",
    category: "Healthcare",
    impactScore: 81,
    updatedAt: "2026-03-11",
    summary:
      "Rank outreach by risk band, last visit, care gap, location, and language.",
  },
  {
    id: "REC-1032",
    project: "Security training gaps",
    owner: "Elias Park",
    status: "Done",
    priority: "Medium",
    category: "Security",
    impactScore: 75,
    updatedAt: "2026-03-08",
    summary:
      "Show overdue modules, risky departments, phishing outcomes, and exemptions.",
  },
  {
    id: "REC-1033",
    project: "Product feedback matrix",
    owner: "Sam Rivera",
    status: "In Progress",
    priority: "Medium",
    category: "Product",
    impactScore: 79,
    updatedAt: "2026-03-05",
    summary:
      "Merge feedback by theme, account value, frequency, product area, and status.",
  },
  {
    id: "REC-1034",
    project: "Board packet builder",
    owner: "Priya Shah",
    status: "Blocked",
    priority: "High",
    category: "Finance",
    impactScore: 83,
    updatedAt: "2026-03-01",
    summary:
      "Blocked while finance validates the final monthly close workbook.",
  },
  {
    id: "REC-1035",
    project: "Maintenance parts planner",
    owner: "Iris Kim",
    status: "Review",
    priority: "Medium",
    category: "Manufacturing",
    impactScore: 74,
    updatedAt: "2026-02-26",
    summary:
      "Forecast parts need from maintenance plans, lead times, and failure history.",
  },
  {
    id: "REC-1036",
    project: "Local ordinance tracker",
    owner: "Hannah Lee",
    status: "In Progress",
    priority: "Low",
    category: "Public Sector",
    impactScore: 60,
    updatedAt: "2026-02-22",
    summary:
      "Track proposed ordinances by topic, sponsor, hearings, and public comments.",
  },
];
